[project]
name = "alberta-rent-watch"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "zsaghir", email = "zsaghir@ualberta.ca" }
]
requires-python = ">=3.9"
dependencies = [
    "polars>=1.36.1",
]

[project.scripts]
alberta-rent-watch = "alberta_rent_watch:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "ipykernel>=6.31.0",
    "pytest>=8.4.2",
    "ruff>=0.16.3",
]
